version: "3.3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
#    restart: always
#    volumes:
#      - redis_volume_data:/data
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    ports:
      - "8001:8001"
#    restart: always
#    volumes:
#      - redis_insight_volume_data:/db
#volumes:
#  redis_volume_data:
#  redis_insight_volume_data: